name: BreakWarn
version: 1.0
api: 4.0.0
main: GLX20\BreakWarn\Main
author: GLX20

commands:
  breakwarn:
    permission: breakwarn.allow
    description: "Warns players before their tool Breaks --- Help: /breakwarn help"
    permission-message: "No permission for Breakwarn"


permissions:
  breakwarn.allow:
    default: true

