name: BreakWarn
version: 1.1
api: 4.0.0
main: GLX20\BreakWarn\Main
author: GLX20

commands:
  breakwarn:
    permission: breakwarn.allow
    description: "Warns players before their tool breaks --- Help: /breakwarn help"
    permission-message: "No permission for BreakWarn"


permissions:
  breakwarn.allow:
    default: true
  breakwarn.tool:
    default: op
