name: BreakWarn
version: 1.2
api: 4.0.0
main: GLX20\BreakWarn\Main
author: GLX20


permissions:
  breakwarn.allow:
    default: true
    description: "let you use BreakWarn command mode"
  breakwarn.tool:
    default: op
    description: "let you use BreakWarn tool mode"
